"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useApp } from "@/components/AppProvider";
import { recommendCompanies, roleSummariesForCompany, type Company } from "@/lib/companies";
import { ROLES } from "@/lib/roles";
import { analyzeText, generateCoverLetter, generateEmail } from "@/lib/client";
import type { JobDraft } from "@/components/AddJobModal";

interface Suggestion {
  key: string;
  company: Company;
  role: string;
  summary: string;
  skills: string[];
  salary: string;
  score: number;
}

interface AutopilotResult {
  key: string;
  title: string;
  company: string;
  score: number;
  coverLetter: string;
  emailSubject: string;
  emailBody: string;
  jobUrl: string;
}

function jdFor(company: Company, role: string, skills: string[]): string {
  return [
    `Role: ${role}`,
    `Company: ${company.name}`,
    `Industry: ${company.industry}`,
    `Key skills: ${skills.join(", ")}.`,
    `We are hiring a ${role} at ${company.name}. In this role you will apply ${skills.slice(0, 3).join(", ")}, and related tools, to deliver measurable results. You should be able to explain your past projects, the problem you solved, and the impact you created.`,
    `This posting is a suggested role profile generated by FitCheck Autopilot, not a live employer posting.`,
  ].join("\n\n");
}

export default function AutopilotPage() {
  const { ws, jobs, addJob, analyzeJob } = useApp();
  const [running, setRunning] = useState(false);
  const [results, setResults] = useState<AutopilotResult[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [visibleCount, setVisibleCount] = useState(6);
  const [progress, setProgress] = useState("");
  const [failed, setFailed] = useState<string[]>([]);

  const suggestions = useMemo<Suggestion[]>(() => {
    const companies = recommendCompanies(ws.profile, ws.masterResume?.text ?? "", 10);
    const existing = new Set(jobs.map((j) => `${j.company?.toLowerCase()}|${j.title?.toLowerCase()}`));
    const out: Suggestion[] = [];
    for (const company of companies) {
      const roles = roleSummariesForCompany(company);
      for (const roleInfo of roles.slice(0, 2)) {
        const role = roleInfo.title;
        const key = `${company.id}|${role.toLowerCase()}`;
        if (existing.has(`${company.name.toLowerCase()}|${role.toLowerCase()}`)) continue;
        const info = ROLES.find((r) => r.title === role);
        out.push({
          key,
          company,
          role,
          summary: roleInfo.summary,
          skills: roleInfo.requirements,
          salary: info ? `$${Math.round(info.salaryMin / 1000)}k–$${Math.round(info.salaryMax / 1000)}k` : "Salary varies",
          score: company.score + (ws.profile?.targetRoles.includes(company.id) ? 2 : 0),
        });
      }
    }
    out.sort((a, b) => b.score - a.score || a.company.name.localeCompare(b.company.name));
    return out.slice(0, 6);
  }, [ws.profile, ws.masterResume?.text, jobs]);

  async function runAutopilot() {
    if (!ws.masterResume?.text || suggestions.length === 0) return;
    setRunning(true);
    setError(null);
    setResults([]);
    setVisibleCount(6);
    setFailed([]);
    setProgress(`0/${suggestions.length}`);
    const collected: AutopilotResult[] = [];
    const failures: string[] = [];
    let index = 0;
    for (const s of suggestions) {
      index += 1;
      setProgress(`${index}/${suggestions.length}`);
      try {
        const draft: JobDraft = {
          title: s.role,
          company: s.company.name,
          url: s.company.careersUrl,
          location: ws.profile?.remotePreference || "Remote",
          salary: s.salary,
          notes: `Autopilot suggestion · ${s.company.industry}`,
          contacts: [],
          jdText: jdFor(s.company, s.role, s.skills),
        };
        const id = addJob(draft, "saved");
        await analyzeJob(id);
        const analysis = await analyzeText(ws.masterResume.text, draft.jdText).catch(() => null);
        const cover = await generateCoverLetter({
          jobDescription: draft.jdText,
          resumeText: ws.masterResume.text,
          company: s.company.name,
          role: s.role,
          profile: ws.profile,
        });
        const email = await generateEmail({
          jobDescription: draft.jdText,
          resumeText: ws.masterResume.text,
          purpose: "outreach",
          company: s.company.name,
          role: s.role,
        });
        collected.push({
          key: s.key,
          title: s.role,
          company: s.company.name,
          score: analysis?.overallScore ?? s.score,
          coverLetter: cover,
          emailSubject: email.subject,
          emailBody: email.body,
          jobUrl: s.company.careersUrl,
        });
      } catch {
        failures.push(`${s.role} @ ${s.company.name}`);
      }
    }
    setResults(collected);
    setFailed(failures);
    setProgress("");
    setRunning(false);
  }

  async function copyText(text: string) {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // clipboard unavailable
    }
  }

  async function copyAll() {
    const text = results
      .map(
        (r) =>
          `===== ${r.title} · ${r.company} =====\n\nCOVER LETTER\n${r.coverLetter}\n\nEMAIL\nSubject: ${r.emailSubject}\n\n${r.emailBody}`,
      )
      .join("\n\n\n");
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // clipboard unavailable
    }
  }

  return (
    <div className="space-y-6">
      <section className="card p-5">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h2 className="text-sm font-bold text-slate-900">Autopilot</h2>
            <p className="mt-0.5 max-w-2xl text-xs leading-relaxed text-slate-500">
              From your resume + profile, it tracks the top roles, scores them, and drafts a cover letter and outreach
              email for each. You only review and send.
            </p>
          </div>
          <button
            type="button"
            onClick={() => void runAutopilot()}
            disabled={running || suggestions.length === 0 || !ws.masterResume}
            className="btn-primary btn-sm disabled:cursor-not-allowed disabled:bg-slate-300"
          >
            {running ? `Running ${progress}…` : `⚡ Run Autopilot (${suggestions.length})`}
          </button>
        </div>
        {!ws.masterResume && (
          <p className="mt-3 text-xs text-slate-500">
            Upload a resume first. <Link href="/resume" className="font-semibold text-brand-600 hover:underline">Go to Resume Studio →</Link>
          </p>
        )}
        {error && <p className="mt-3 text-xs font-medium text-rose-600">{error}</p>}
        {failed.length > 0 && (
          <div className="mt-3 rounded-lg bg-rose-50 p-3">
            <p className="text-xs font-semibold text-rose-700">
              {failed.length} suggestion{failed.length === 1 ? "" : "s"} could not be processed:
            </p>
            <p className="mt-1 text-xs text-rose-600">{failed.join(" · ")}</p>
            <button type="button" onClick={() => void runAutopilot()} className="btn-secondary btn-sm mt-2">
              Retry
            </button>
          </div>
        )}
      </section>

      {suggestions.length > 0 && !running && results.length === 0 && (
        <section className="card p-5">
          <h3 className="text-sm font-bold text-slate-900">Top suggestions</h3>
          <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {suggestions.map((s) => (
              <div key={s.key} className="rounded-xl border border-slate-200 bg-slate-50/60 p-3">
                <p className="text-sm font-semibold text-slate-800">{s.role}</p>
                <p className="text-xs text-slate-500">{s.company.name} · {s.salary}</p>
                <span className="chip mt-2 bg-brand-50 text-brand-700">{s.score} match</span>
              </div>
            ))}
          </div>
        </section>
      )}

      {results.length > 0 && (
        <section className="space-y-4">
          <div className="flex justify-end">
            <button type="button" onClick={() => void copyAll()} className="btn-primary btn-sm">
              Copy all drafts
            </button>
          </div>
          {results.slice(0, visibleCount).map((r) => (
            <div key={r.key} className="card p-5">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <p className="text-sm font-semibold text-slate-900">
                    {r.title} <span className="font-normal text-slate-500">· {r.company}</span>
                  </p>
                  <p className="text-xs text-slate-400">Score {r.score} · job added to Applications</p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <a href={r.jobUrl} target="_blank" rel="noreferrer" className="btn-secondary btn-sm">
                    Careers ↗
                  </a>
                  <button type="button" onClick={() => void copyText(r.coverLetter)} className="btn-secondary btn-sm">
                    Copy cover letter
                  </button>
                  <button
                    type="button"
                    onClick={() => void copyText(`Subject: ${r.emailSubject}\n\n${r.emailBody}`)}
                    className="btn-primary btn-sm"
                  >
                    Copy email
                  </button>
                </div>
              </div>
              <div className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-2">
                <textarea value={r.coverLetter} readOnly rows={8} className="field resize-y whitespace-pre-wrap text-xs leading-relaxed" />
                <textarea
                  value={`Subject: ${r.emailSubject}\n\n${r.emailBody}`}
                  readOnly
                  rows={8}
                  className="field resize-y whitespace-pre-wrap text-xs leading-relaxed"
                />
              </div>
            </div>
          ))}
          {results.length > visibleCount && (
            <div className="flex justify-center">
              <button type="button" onClick={() => setVisibleCount((count) => count + 6)} className="btn-secondary">
                Show more
              </button>
            </div>
          )}
          <p className="text-center text-xs text-slate-400">
            Review every draft and verify facts before sending. Autopilot drafts, it does not apply for you.
          </p>
        </section>
      )}
    </div>
  );
}
